import polo from "@/assets/product-polo.jpg";
import poloNavy from "@/assets/product-polo-navy-clean.jpg";
import poloCream from "@/assets/product-polo-cream.jpg";
import gurkha from "@/assets/product-gurkha.jpg";
import gurkhaStone from "@/assets/product-gurkha-stone.jpg";
import gurkhaDetailNavy from "@/assets/gurkha-detail.jpg";
import linen from "@/assets/product-linen.jpg";
import linenBlue from "@/assets/product-linen-blue.jpg";
import linenSand from "@/assets/product-linen-sand.jpg";
import chino from "@/assets/product-chino.jpg";
import chinoSand from "@/assets/product-chino-sand.jpg";
import chinoNavy from "@/assets/product-chino-navy.jpg";
import lookbook1 from "@/assets/lookbook-1.jpg";
import lookbook2 from "@/assets/lookbook-2.jpg";
import lookbook3 from "@/assets/lookbook-3.jpg";
import insta2 from "@/assets/insta-2.jpg";
import insta6 from "@/assets/insta-6.jpg";
import knitFlat from "@/assets/journal-2.jpg";

import dPoloSage from "@/assets/details/detail-polo-sage.jpg";
import dPoloNavy from "@/assets/details/detail-polo-navy.jpg";
import dPoloCream from "@/assets/details/detail-polo-cream.jpg";
import dPoloStone from "@/assets/details/detail-polo-stone.jpg";
import dPoloBlanc from "@/assets/details/detail-polo-blanc.jpg";
import dLinenWhite from "@/assets/details/detail-linen-white.jpg";
import dLinenBlue from "@/assets/details/detail-linen-blue.jpg";
import dLinenSand from "@/assets/details/detail-linen-sand.jpg";
import dLinenAir from "@/assets/details/detail-linen-air.jpg";
import dChinoOlive from "@/assets/details/detail-chino-olive.jpg";
import dChinoSand from "@/assets/details/detail-chino-sand.jpg";
import dChinoNavy from "@/assets/details/detail-chino-navy.jpg";
import dGurkhaCream from "@/assets/details/detail-gurkha-cream.jpg";
import dGurkhaStone from "@/assets/details/detail-gurkha-stone.jpg";
import dKnitCamel from "@/assets/details/detail-knit-camel.jpg";
import dKnitTaupe from "@/assets/details/detail-knit-taupe.jpg";
import dKnitFold from "@/assets/details/detail-knit-fold.jpg";
import dLoafer from "@/assets/details/detail-loafer.jpg";
import insta4 from "@/assets/insta-4.jpg";
import teeCream from "@/assets/details/product-tee-cream.jpg";
import dTeeCream from "@/assets/details/detail-tee-cream.jpg";
import trouserSand from "@/assets/details/product-trouser-sand.jpg";
import trouserTaupe from "@/assets/details/product-trouser-taupe.jpg";
import trouserIvory from "@/assets/details/product-trouser-ivory.jpg";
import knitOat from "@/assets/details/product-knit-oat.jpg";
import dPoplinCuff from "@/assets/details/detail-poplin-cuff.jpg";
import dLinenOstuni from "@/assets/details/detail-linen-ostuni.jpg";

export type Category = "Polos" | "Linen Shirts" | "Gurkhas" | "Chinos" | "Knitwear" | "Footwear";

export type Product = {
  slug: string;
  name: string;
  category: Category;
  price: number;
  compareAt?: number;
  image: string;
  images: string[];
  tagline: string;
  color: string;
  colorHex: string;
  fabric: string;
  fit: string;
  details: string[];
  care: string;
  badge?: "New Season" | "Bestseller" | "Signature" | "Nearly Gone" | "Icon";
  rating: number;
  reviews: number;
  colorways: string[]; // sibling slugs of the same garment
  styledWith: string[]; // slugs for "Complete the Look"
  modelNote?: string;
};

export const products: Product[] = [
  // ——— Polos ———
  {
    slug: "riviera-sage-polo",
    name: "Riviera Polo",
    category: "Polos",
    price: 2790,
    image: polo,
    images: [polo, dPoloSage],
    tagline: "220 GSM Pima piqué, tailored fit.",
    color: "Sage",
    colorHex: "#9AA98C",
    fabric: "100% Peruvian Pima cotton piqué, 220 GSM",
    fit: "Tailored — trim through the chest, gentle ease at the waist. Sits at mid-hip.",
    details: [
      "Genuine mother-of-pearl buttons",
      "Single-piece knitted collar that won't curl",
      "Side vents with reinforced bar tacks",
      "Pre-washed to eliminate shrinkage",
    ],
    care: "Machine wash cold, inside out. Lay flat to dry. Warm iron if needed.",
    badge: "Bestseller",
    rating: 4.8,
    reviews: 214,
    colorways: ["monaco-navy-polo", "amalfi-cream-polo", "portofino-stone-polo", "cafe-blanc-polo"],
    styledWith: ["monaco-cream-gurkha", "torino-sand-chino", "firenze-penny-loafer"],
    modelNote: "Aditya is 6'0\" (183 cm) and wears a size M.",
  },
  {
    slug: "monaco-navy-polo",
    name: "Monaco Polo",
    category: "Polos",
    price: 2790,
    image: poloNavy,
    images: [poloNavy, dPoloNavy],
    tagline: "The studio essential, garment-dyed.",
    color: "Navy",
    colorHex: "#232E3D",
    fabric: "100% Peruvian Pima cotton piqué, 220 GSM",
    fit: "Tailored — trim through the chest, gentle ease at the waist. Sits at mid-hip.",
    details: [
      "Genuine mother-of-pearl buttons, dyed to tone",
      "Single-piece knitted collar that won't curl",
      "Side vents with reinforced bar tacks",
      "Garment-dyed for depth that improves with wear",
    ],
    care: "Machine wash cold, inside out. Lay flat to dry. Warm iron if needed.",
    rating: 4.9,
    reviews: 186,
    colorways: ["riviera-sage-polo", "amalfi-cream-polo", "portofino-stone-polo", "cafe-blanc-polo"],
    styledWith: ["torino-sand-chino", "bellagio-stone-gurkha", "firenze-penny-loafer"],
    modelNote: "Aditya is 6'0\" (183 cm) and wears a size M.",
  },
  {
    slug: "amalfi-cream-polo",
    name: "Amalfi Polo",
    category: "Polos",
    price: 2890,
    image: poloCream,
    images: [poloCream, dPoloCream],
    tagline: "Undyed ecru piqué for golden hour.",
    color: "Cream",
    colorHex: "#EFE9DA",
    fabric: "100% Peruvian Pima cotton piqué, 220 GSM",
    fit: "Tailored — trim through the chest, gentle ease at the waist. Sits at mid-hip.",
    details: [
      "Genuine mother-of-pearl buttons",
      "Single-piece knitted collar that won't curl",
      "Side vents with reinforced bar tacks",
      "Undyed ecru yarn — no optical brighteners",
    ],
    care: "Machine wash cold, inside out. Lay flat to dry. Warm iron if needed.",
    rating: 4.7,
    reviews: 143,
    colorways: ["riviera-sage-polo", "monaco-navy-polo", "portofino-stone-polo", "cafe-blanc-polo"],
    styledWith: ["verona-navy-chino", "firenze-penny-loafer"],
    modelNote: "Aditya is 6'0\" (183 cm) and wears a size M.",
  },
  {
    slug: "portofino-stone-polo",
    name: "Portofino Polo",
    category: "Polos",
    price: 2890,
    image: insta6,
    images: [insta6, dPoloStone],
    tagline: "Mineral-dyed piqué, shot off Portofino.",
    color: "Stone",
    colorHex: "#C9BFAE",
    fabric: "100% Peruvian Pima cotton piqué, 220 GSM",
    fit: "Tailored — trim through the chest, gentle ease at the waist. Sits at mid-hip.",
    details: [
      "Genuine mother-of-pearl buttons",
      "Single-piece knitted collar that won't curl",
      "Side vents with reinforced bar tacks",
      "Mineral-dyed in small batches — expect slight variation",
    ],
    care: "Machine wash cold, inside out. Lay flat to dry. Warm iron if needed.",
    badge: "New Season",
    rating: 4.8,
    reviews: 57,
    colorways: ["riviera-sage-polo", "monaco-navy-polo", "amalfi-cream-polo", "cafe-blanc-polo"],
    styledWith: ["torino-sand-chino", "monaco-cream-gurkha", "firenze-penny-loafer"],
    modelNote: "Rohan is 6'1\" (185 cm) and wears a size L.",
  },
  {
    slug: "cafe-blanc-polo",
    name: "Café Blanc Polo",
    category: "Polos",
    price: 2890,
    image: lookbook3,
    images: [lookbook3, dPoloBlanc],
    tagline: "Double-mercerised piqué, café to coastline.",
    color: "White",
    colorHex: "#F4F2EC",
    fabric: "100% Peruvian Pima cotton piqué, 220 GSM",
    fit: "Tailored — trim through the chest, gentle ease at the waist. Sits at mid-hip.",
    details: [
      "Genuine mother-of-pearl buttons",
      "Single-piece knitted collar that won't curl",
      "Side vents with reinforced bar tacks",
      "Double-mercerised yarn for a quiet lustre",
    ],
    badge: "New Season",
    care: "Machine wash cold, inside out. Lay flat to dry. Warm iron if needed.",
    rating: 4.9,
    reviews: 41,
    colorways: ["riviera-sage-polo", "monaco-navy-polo", "amalfi-cream-polo", "portofino-stone-polo"],
    styledWith: ["monaco-cream-gurkha", "firenze-penny-loafer", "sorrento-merino-crew"],
    modelNote: "Marco is 6'0\" (183 cm) and wears a size M.",
  },

  // ——— Linen Shirts ———
  {
    slug: "amalfi-linen-shirt",
    name: "Amalfi Linen Shirt",
    category: "Linen Shirts",
    price: 3490,
    image: linen,
    images: [linen, dLinenWhite],
    tagline: "European flax, relaxed silhouette.",
    color: "White",
    colorHex: "#F5F3EC",
    fabric: "100% European flax linen, 185 GSM — certified European Flax®",
    fit: "Relaxed — cut with room through the body, curved hem. Wear open or tucked.",
    details: [
      "Corozo nut buttons, hand-finished",
      "Single-needle felled side seams",
      "Chest patch pocket, pattern-matched",
      "Garment-washed for a broken-in hand feel from day one",
    ],
    care: "Machine wash cold. Hang dry. Embrace the wrinkles — that's the point.",
    badge: "Icon",
    rating: 4.9,
    reviews: 312,
    colorways: ["capri-blue-linen", "siena-sand-linen", "riviera-air-linen"],
    styledWith: ["torino-sand-chino", "bellagio-stone-gurkha", "firenze-penny-loafer"],
    modelNote: "Julien is 6'1\" (185 cm) and wears a size M.",
  },
  {
    slug: "capri-blue-linen",
    name: "Capri Linen Shirt",
    category: "Linen Shirts",
    price: 3590,
    image: linenBlue,
    images: [linenBlue, dLinenBlue],
    tagline: "Yarn-dyed, breathable open weave.",
    color: "Capri Blue",
    colorHex: "#AFC4D6",
    fabric: "100% European flax linen, 185 GSM — certified European Flax®",
    fit: "Relaxed — cut with room through the body, curved hem. Wear open or tucked.",
    details: [
      "Corozo nut buttons, hand-finished",
      "Single-needle felled side seams",
      "Yarn-dyed before weaving for lasting colour",
      "Garment-washed for softness",
    ],
    care: "Machine wash cold. Hang dry. Warm iron while damp for a cleaner look.",
    rating: 4.7,
    reviews: 168,
    colorways: ["amalfi-linen-shirt", "siena-sand-linen", "riviera-air-linen"],
    styledWith: ["monaco-cream-gurkha", "torino-sand-chino", "firenze-penny-loafer"],
    modelNote: "Julien is 6'1\" (185 cm) and wears a size M.",
  },
  {
    slug: "siena-sand-linen",
    name: "Siena Linen Shirt",
    category: "Linen Shirts",
    price: 3490,
    image: linenSand,
    images: [linenSand, dLinenSand],
    tagline: "Sun-bleached, stone-washed flax.",
    color: "Sand",
    colorHex: "#D9CBB2",
    fabric: "100% European flax linen, 185 GSM — certified European Flax®",
    fit: "Relaxed — cut with room through the body, curved hem. Wear open or tucked.",
    details: [
      "Corozo nut buttons, hand-finished",
      "Single-needle felled side seams",
      "Pigment-dyed, then stone-washed for a faded patina",
      "Chest patch pocket, pattern-matched",
    ],
    care: "Machine wash cold. Hang dry. Colour softens beautifully over seasons.",
    rating: 4.8,
    reviews: 97,
    colorways: ["amalfi-linen-shirt", "capri-blue-linen", "riviera-air-linen"],
    styledWith: ["verona-navy-chino", "firenze-penny-loafer"],
    modelNote: "Julien is 6'1\" (185 cm) and wears a size M.",
  },
  {
    slug: "riviera-air-linen",
    name: "Riviera Air Shirt",
    category: "Linen Shirts",
    price: 3790,
    image: lookbook2,
    images: [lookbook2, dLinenAir, lookbook1],
    tagline: "Featherweight 145 GSM — our lightest weave.",
    color: "Ivory",
    colorHex: "#F0EBDD",
    fabric: "100% European flax linen, 145 GSM open weave — our lightest shirt",
    fit: "Relaxed — cut with room through the body, curved hem. Drapes rather than sits.",
    details: [
      "Woven at a family mill in Normandy",
      "Corozo nut buttons, hand-finished",
      "Breast pocket sized for sunglasses",
      "Sold with a spare button card, stitched not glued",
    ],
    care: "Hand wash or machine cold on gentle. Hang dry away from direct sun.",
    badge: "New Season",
    rating: 4.9,
    reviews: 36,
    colorways: ["amalfi-linen-shirt", "capri-blue-linen", "siena-sand-linen"],
    styledWith: ["torino-sand-chino", "monaco-cream-gurkha", "firenze-penny-loafer"],
    modelNote: "Luca is 6'2\" (188 cm) and wears a size L.",
  },

  // ——— Chinos ———
  {
    slug: "milano-olive-chino",
    name: "Milano Chino",
    category: "Chinos",
    price: 3290,
    image: chino,
    images: [chino, dChinoOlive],
    tagline: "Garment-dyed twill, slim taper.",
    color: "Olive",
    colorHex: "#6B7355",
    fabric: "98% organic cotton, 2% elastane — 260 GSM brushed twill",
    fit: "Slim taper — trim thigh, gradual taper to a 16 cm leg opening. Mid-rise.",
    details: [
      "Garment-dyed after sewing for tonal depth",
      "Horn-effect corozo fly buttons",
      "Hidden coin pocket with chambray facing",
      "Chain-stitched hems — can be altered by any tailor",
    ],
    care: "Machine wash cold with like colours. Hang dry. Iron inside out.",
    badge: "Bestseller",
    rating: 4.8,
    reviews: 201,
    colorways: ["torino-sand-chino", "verona-navy-chino"],
    styledWith: ["big-sur-merino-crew", "riviera-sage-polo", "firenze-penny-loafer"],
    modelNote: "Daniel is 6'0\" (183 cm) and wears a 32.",
  },
  {
    slug: "torino-sand-chino",
    name: "Torino Chino",
    category: "Chinos",
    price: 3290,
    image: chinoSand,
    images: [chinoSand, dChinoSand],
    tagline: "Brushed twill, coastal cut.",
    color: "Sand",
    colorHex: "#CDBB9C",
    fabric: "98% organic cotton, 2% elastane — 260 GSM brushed twill",
    fit: "Slim taper — trim thigh, gradual taper to a 16 cm leg opening. Mid-rise.",
    details: [
      "Garment-dyed after sewing for tonal depth",
      "Horn-effect corozo fly buttons",
      "Hidden coin pocket with chambray facing",
      "Chain-stitched hems — can be altered by any tailor",
    ],
    care: "Machine wash cold with like colours. Hang dry. Iron inside out.",
    rating: 4.7,
    reviews: 154,
    colorways: ["milano-olive-chino", "verona-navy-chino"],
    styledWith: ["monaco-navy-polo", "amalfi-linen-shirt", "firenze-penny-loafer"],
    modelNote: "Daniel is 6'0\" (183 cm) and wears a 32.",
  },
  {
    slug: "verona-navy-chino",
    name: "Verona Chino",
    category: "Chinos",
    price: 3390,
    image: chinoNavy,
    images: [chinoNavy, dChinoNavy],
    tagline: "Crisp twill, tailored taper.",
    color: "Navy",
    colorHex: "#28313E",
    fabric: "98% organic cotton, 2% elastane — 260 GSM brushed twill",
    fit: "Slim taper — trim thigh, gradual taper to a 16 cm leg opening. Mid-rise.",
    details: [
      "Garment-dyed after sewing for tonal depth",
      "Horn-effect corozo fly buttons",
      "Hidden coin pocket with chambray facing",
      "Chain-stitched hems — can be altered by any tailor",
    ],
    care: "Machine wash cold with like colours. Hang dry. Iron inside out.",
    rating: 4.8,
    reviews: 119,
    colorways: ["milano-olive-chino", "torino-sand-chino"],
    styledWith: ["amalfi-cream-polo", "siena-sand-linen", "firenze-penny-loafer"],
    modelNote: "Daniel is 6'0\" (183 cm) and wears a 32.",
  },

  // ——— Gurkhas ———
  {
    slug: "monaco-cream-gurkha",
    name: "Monaco Gurkha",
    category: "Gurkhas",
    price: 4990,
    image: gurkha,
    images: [gurkha, dGurkhaCream],
    tagline: "Double-pleat, self-belt, high rise.",
    color: "Cream",
    colorHex: "#EEE6D2",
    fabric: "Cotton-lyocell twill, 280 GSM — dry hand, fluid drape",
    fit: "High-rise, double forward pleats, full through the thigh with a deep taper.",
    details: [
      "Signature double self-belt with antique-brass D-rings",
      "Extended curtain waistband, hand-tacked",
      "Slant pockets cut on the bias to stay closed",
      "Pick-stitched fly and pocket openings",
    ],
    care: "Dry clean recommended. Steam between wears.",
    badge: "Signature",
    rating: 4.9,
    reviews: 178,
    colorways: ["bellagio-stone-gurkha", "marina-navy-gurkha"],
    styledWith: ["cafe-blanc-polo", "amalfi-linen-shirt", "firenze-penny-loafer"],
    modelNote: "Théo is 6'2\" (188 cm) and wears a 32.",
  },
  {
    slug: "bellagio-stone-gurkha",
    name: "Bellagio Gurkha",
    category: "Gurkhas",
    price: 5190,
    image: gurkhaStone,
    images: [gurkhaStone, dGurkhaStone],
    tagline: "Antique-brass buckle, deep taper.",
    color: "Stone",
    colorHex: "#B6AC9C",
    fabric: "Cotton-lyocell twill, 280 GSM — dry hand, fluid drape",
    fit: "High-rise, double forward pleats, full through the thigh with a deep taper.",
    details: [
      "Signature double self-belt with antique-brass D-rings",
      "Extended curtain waistband, hand-tacked",
      "Slant pockets cut on the bias to stay closed",
      "Pick-stitched fly and pocket openings",
    ],
    care: "Dry clean recommended. Steam between wears.",
    rating: 4.7,
    reviews: 96,
    colorways: ["monaco-cream-gurkha", "marina-navy-gurkha"],
    styledWith: ["monaco-navy-polo", "amalfi-linen-shirt", "firenze-penny-loafer"],
    modelNote: "Théo is 6'2\" (188 cm) and wears a 32.",
  },
  {
    slug: "marina-navy-gurkha",
    name: "Marina Gurkha",
    category: "Gurkhas",
    price: 5390,
    image: gurkhaDetailNavy,
    images: [gurkhaDetailNavy],
    tagline: "Evening hopsack — reads black by candlelight.",
    color: "Midnight Navy",
    colorHex: "#1C2430",
    fabric: "Cotton-linen hopsack, 300 GSM — matte surface, crisp structure",
    fit: "High-rise, double forward pleats, full through the thigh with a deep taper.",
    details: [
      "Signature double self-belt with antique-brass D-rings",
      "Extended curtain waistband, hand-tacked",
      "Woven in a deep indigo that reads black by candlelight",
      "Pick-stitched fly and pocket openings",
    ],
    care: "Dry clean recommended. Steam between wears.",
    badge: "Nearly Gone",
    rating: 4.9,
    reviews: 64,
    colorways: ["monaco-cream-gurkha", "bellagio-stone-gurkha"],
    styledWith: ["cafe-blanc-polo", "amalfi-linen-shirt", "firenze-penny-loafer"],
  },

  // ——— Knitwear ———
  {
    slug: "sorrento-merino-crew",
    name: "Sorrento Merino Crew",
    category: "Knitwear",
    price: 5490,
    image: dKnitCamel,
    images: [dKnitCamel, dKnitFold],
    tagline: "Extra-fine merino, 12-gauge knit.",
    color: "Camel",
    colorHex: "#C7A886",
    fabric: "100% extra-fine merino wool, 19.5 micron — 12-gauge knit",
    fit: "Regular — follows the body without clinging. Ribbed hem and cuffs.",
    details: [
      "Fully-fashioned sleeves — knitted to shape, not cut",
      "Seamless collar linking, done by hand",
      "Ribbed side panels for ease of movement",
      "Naturally odour-resistant; wear, air, repeat",
    ],
    care: "Hand wash cold or dry clean. Store folded, never hung.",
    badge: "New Season",
    rating: 4.9,
    reviews: 48,
    colorways: ["big-sur-merino-crew", "positano-ribbed-crew"],
    styledWith: ["verona-navy-chino", "cafe-blanc-polo", "firenze-penny-loafer"],
  },
  {
    slug: "big-sur-merino-crew",
    name: "Big Sur Merino Crew",
    category: "Knitwear",
    price: 5490,
    image: chino,
    images: [chino, dKnitTaupe],
    tagline: "As worn with the Milano Chino.",
    color: "Taupe",
    colorHex: "#9E8E7A",
    fabric: "100% extra-fine merino wool, 19.5 micron — 12-gauge knit",
    fit: "Regular — follows the body without clinging. Ribbed hem and cuffs.",
    details: [
      "Fully-fashioned sleeves — knitted to shape, not cut",
      "Seamless collar linking, done by hand",
      "Ribbed side panels for ease of movement",
      "Pictured with the Milano Chino in Olive",
    ],
    care: "Hand wash cold or dry clean. Store folded, never hung.",
    rating: 4.8,
    reviews: 39,
    colorways: ["sorrento-merino-crew", "positano-ribbed-crew"],
    styledWith: ["milano-olive-chino", "verona-navy-chino", "firenze-penny-loafer"],
    modelNote: "Daniel is 6'0\" (183 cm) and wears a size M.",
  },

  // ——— Footwear ———
  {
    slug: "firenze-penny-loafer",
    name: "Firenze Penny Loafer",
    category: "Footwear",
    price: 8990,
    image: insta2,
    images: [insta2, dLoafer],
    tagline: "Hand-stitched calf. First of the line.",
    color: "Espresso",
    colorHex: "#4A3226",
    fabric: "Full-grain Italian calf leather, vegetable-tanned. Leather-lined.",
    fit: "True to size with a medium width. Between sizes, take the half size down.",
    details: [
      "Genuine hand-sewn moccasin construction",
      "Blake-stitched sole — resoleable for life",
      "Unstructured toe that moulds to the foot",
      "Our first footwear release — numbered run of 300 pairs",
    ],
    care: "Cedar shoe trees between wears. Condition monthly with neutral cream.",
    badge: "New Season",
    rating: 4.9,
    reviews: 27,
    colorways: [],
    styledWith: ["monaco-cream-gurkha", "riviera-sage-polo", "verona-navy-chino"],
  },
  // ——— Second drop ———
  {
    slug: "terrazza-cotton-tee",
    name: "Terrazza Cotton Tee",
    category: "Polos",
    price: 1990,
    image: teeCream,
    images: [teeCream, dTeeCream],
    tagline: "Heavyweight interlock, as worn with the Monaco Gurkha.",
    color: "Écru",
    colorHex: "#F0E8D6",
    fabric: "100% Supima cotton interlock, 240 GSM",
    fit: "Regular — clean through the body with a mid-weight drape. Sits at high hip.",
    details: [
      "Tubular-knit body — no side seams to twist",
      "Self-fabric collar rib, cut on the round",
      "Shoulder-to-shoulder taping",
      "Pictured with the Monaco Gurkha in Cream",
    ],
    care: "Machine wash cold, inside out. Lay flat to dry.",
    badge: "New Season",
    rating: 4.8,
    reviews: 52,
    colorways: [],
    styledWith: ["monaco-cream-gurkha", "milano-olive-chino", "firenze-penny-loafer"],
    modelNote: "Théo is 6'2\" (188 cm) and wears a size M.",
  },
  {
    slug: "ostuni-linen-shirt",
    name: "Ostuni Linen Shirt",
    category: "Linen Shirts",
    price: 3690,
    image: dLinenOstuni,
    images: [dLinenOstuni, lookbook1],
    tagline: "Open gauze weave, cut for the heat.",
    color: "Salt White",
    colorHex: "#F2EEE3",
    fabric: "100% European flax linen gauze, 160 GSM — our airiest weave after the Riviera Air",
    fit: "Relaxed — generous through the chest with a longer curved hem. Best worn open-collared.",
    details: [
      "Loose gauze weave that moves air, not heat",
      "Corozo nut buttons, hand-finished",
      "Cutaway collar that sits open without collapsing",
      "Photographed in Ostuni at last light",
    ],
    care: "Machine wash cold on gentle. Hang dry. Never tumble.",
    badge: "New Season",
    rating: 4.8,
    reviews: 44,
    colorways: [],
    styledWith: ["ostuni-pleated-trouser", "fasano-linen-trouser", "firenze-penny-loafer"],
    modelNote: "Matteo is 6'1\" (185 cm) and wears a size L.",
  },
  {
    slug: "marcello-poplin-shirt",
    name: "Marcello Poplin Shirt",
    category: "Linen Shirts",
    price: 3990,
    image: insta4,
    images: [insta4, dPoplinCuff],
    tagline: "Linen-cotton poplin. The evening shirt.",
    color: "Bianco",
    colorHex: "#F7F4EC",
    fabric: "55% European flax, 45% Egyptian cotton poplin — crisp face, soft handle",
    fit: "Tailored — darted back, higher armhole, single-button barrel cuff.",
    details: [
      "The dressed-up counterpoint to our washed linens",
      "Single-needle stitching throughout, 18 stitches per inch",
      "Removable collar stays in natural corozo",
      "Cuff sized to clear a dress watch",
    ],
    care: "Machine wash cold. Hang dry. Iron while damp for a crisp finish.",
    badge: "New Season",
    rating: 4.9,
    reviews: 31,
    colorways: [],
    styledWith: ["marina-navy-gurkha", "verona-navy-chino", "firenze-penny-loafer"],
  },
  {
    slug: "fasano-linen-trouser",
    name: "Fasano Linen Trouser",
    category: "Chinos",
    price: 3590,
    image: trouserSand,
    images: [trouserSand, lookbook2],
    tagline: "Washed linen, drawstring ease.",
    color: "Sand",
    colorHex: "#D3C3A5",
    fabric: "100% European flax linen, 210 GSM — garment-washed",
    fit: "Easy straight — relaxed rise, straight leg, hidden drawstring inside a tailored waistband.",
    details: [
      "Tailored front, drawstring comfort — no visible cords",
      "Garment-washed for a lived-in drape",
      "Deep slash pockets in cotton drill",
      "Pictured with the Riviera Air Shirt",
    ],
    care: "Machine wash cold. Hang dry. Embrace the crease.",
    badge: "New Season",
    rating: 4.7,
    reviews: 38,
    colorways: ["ostuni-pleated-trouser"],
    styledWith: ["riviera-air-linen", "ostuni-linen-shirt", "firenze-penny-loafer"],
    modelNote: "Luca is 6'2\" (188 cm) and wears a 34.",
  },
  {
    slug: "ostuni-pleated-trouser",
    name: "Ostuni Pleated Trouser",
    category: "Chinos",
    price: 3690,
    image: trouserTaupe,
    images: [trouserTaupe, lookbook1],
    tagline: "Single pleat, tropical-weight weave.",
    color: "Taupe",
    colorHex: "#A6937B",
    fabric: "Linen-viscose tropical weave, 230 GSM — dry crisp hand",
    fit: "Pleated straight — single forward pleat, higher rise, fuller leg than our chinos.",
    details: [
      "Single forward pleat pressed to the crease line",
      "Extended waistband tab with hidden hook",
      "Unfinished hem — complimentary alteration in-store",
      "Photographed in Ostuni at last light",
    ],
    care: "Dry clean or careful cold hand wash. Steam between wears.",
    badge: "New Season",
    rating: 4.8,
    reviews: 29,
    colorways: ["fasano-linen-trouser"],
    styledWith: ["ostuni-linen-shirt", "amalfi-linen-shirt", "firenze-penny-loafer"],
    modelNote: "Matteo is 6'1\" (185 cm) and wears a 32.",
  },
  {
    slug: "salotto-gurkha",
    name: "Salotto Gurkha",
    category: "Gurkhas",
    price: 5290,
    image: trouserIvory,
    images: [trouserIvory],
    tagline: "The Gurkha, unbelted — for the drawing room.",
    color: "Ivory",
    colorHex: "#EDE5D3",
    fabric: "Cotton-wool herringbone, 290 GSM — soft structure, matte face",
    fit: "Cut on the Gurkha block without the self-belt: high-rise, single pleat, extended tab waist.",
    details: [
      "Same high-rise block as the signature Gurkha",
      "Extended tab waistband with double hidden hooks",
      "Herringbone weave visible only up close",
      "Pick-stitched fly and pocket openings",
    ],
    care: "Dry clean recommended. Steam between wears.",
    badge: "New Season",
    rating: 4.9,
    reviews: 22,
    colorways: ["monaco-cream-gurkha", "bellagio-stone-gurkha", "marina-navy-gurkha"],
    styledWith: ["marcello-poplin-shirt", "terrazza-cotton-tee", "firenze-penny-loafer"],
  },
  {
    slug: "positano-ribbed-crew",
    name: "Positano Ribbed Crew",
    category: "Knitwear",
    price: 5690,
    image: chinoNavy,
    images: [chinoNavy, knitOat],
    tagline: "Wide-rib merino — as worn with the Verona Chino.",
    color: "Ecru",
    colorHex: "#EAE0CC",
    fabric: "100% extra-fine merino wool, 19.5 micron — 7-gauge wide rib",
    fit: "Regular with give — the rib expands and recovers. Ribbed hem, cuffs and collar.",
    details: [
      "Wide 7-gauge rib for depth and warmth",
      "Fully-fashioned sleeves — knitted to shape, not cut",
      "Seamless collar linking, done by hand",
      "The heaviest knit of our first drop",
    ],
    care: "Hand wash cold or dry clean. Store folded, never hung.",
    badge: "New Season",
    rating: 4.8,
    reviews: 19,
    colorways: ["sorrento-merino-crew", "big-sur-merino-crew"],
    styledWith: ["verona-navy-chino", "salotto-gurkha", "firenze-penny-loafer"],
  },
];

export const bySlug = (slug: string) => products.find((p) => p.slug === slug);
export const byCategory = (c: Category) => products.filter((p) => p.category === c);
export const newArrivals = () => products.filter((p) => p.badge === "New Season");

export const categorySlug = (c: Category) => c.toLowerCase().replace(/\s+/g, "-");

export const formatINR = (n: number) =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n);
